server:
  port: 8088

spring:
  application:
    name: securityTest

  mvc:
    hidden method:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb1?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test1
    password: full405


  jpa:
    database:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      timeout: 2000
      port: 6379







